#!/usr/bin/php
<?php
/**
 * Terminal
 * 
 * @author wadahkode
 * @since version v0.0.1
 */
define('TERMINAL_INPUT', isset($_SERVER['argv']) ? $_SERVER['argv'] : []);

/**
 * Call bootstraping for autoloaded class.
 */

if (file_exists("vendor/autoload.php")) {
    require __DIR__ ."/vendor/autoload.php";

    /**
     * Register your command
     * 
     * ex: php wadahkode serve
     */
    return Wadahkode\Console\Terminal::register(function($terminal){
        return $terminal->execute();
    });
}

// require_once __DIR__.'/bootstrap/app.php';

/**
 * Register your command
 * 
 * ex: php wadahkode serve
 */
// return \Wadahkode\Console\Terminal::register(function($terminal){
//     return $terminal->execute();
// });